stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  script:
    - docker --version
    - docker-compose down
    - docker system prune -f
    - docker-compose build
    - docker-compose up -d
